### ISSUE TITLE
getHtml returns html code with forward slashes around attribute values

### ISSUE THREAD

**Issue by cyberpunk922** [dankito/RichTextEditor#14]
output: 
`"<p>​hi there.... <span style=\"text-decoration-line: underline; background-color: rgb(255, 255, 0);\">This is article upload</span> <span style=\"color: rgb(244, 67, 54); font-weight: bold;\">test 1</span>.</p>"`

issue:
having trouble running this html code in browser. after removing the forward slashes the code runs properly in a browser. please help.

**Comment by dankito** [comment]
Hi,

sorry, I cannot reproduce this issue.

How did you get this html string?

For me neither getCurrentHtmlAsync() (preferred) nor getCachedHtml() (will be removed soon) did return the double quotes escaped, that means with a forward slash.

Did you just copy that string from debugger view in Android Studio (IntelliJ) or Eclipse? Older versions of IntelliJ escaped double quotes in debugger view, but that's not the string's real value.

Could you please tell me which RichTextEditor version and which platform (Android or Java) you used?

Also it would be great if you could provide the steps to reproduce so I can figure out what the issue is.

**Comment by cyberpunk922** [comment]
hi,

I am using RichTextEditor version 2.0.1
method used getCurrentHtmlAsync().
passed the html string value to a string variable and then stored it in fierbase db. 

please take a look at the code below

`private void save() {
        editor.getCurrentHtmlAsync(new GetCurrentHtmlCallback() {

            @Override
            public void htmlRetrieved(@NotNull String html) {
                saveHtml(html);
            }
        });
    }

    private void saveHtml(String html) {
        // ...
        htmlText=html;
    }


    private void savePostToDatabase() {
        userRef.child(currentUserId).addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                if (dataSnapshot.exists())
                {
                    String userfullname = dataSnapshot.child("fullname").getValue().toString();
                    HashMap postMap = new HashMap();
                    postMap.put("uid", currentUserId);
                    postMap.put("date", currentDate);
                    postMap.put("time", currentTime);
                    postMap.put("peronalityname", "TonyStark");
                    postMap.put("articlehtml", htmlText);
                    postMap.put("authorname", userfullname);

                    postsRef.child(currentUserId + randPostName).updateChildren(postMap)
                            .addOnCompleteListener(new OnCompleteListener() {
                                @Override
                                public void onComplete(@NonNull Task task)
                                {

                                    if(task.isSuccessful())
                                    {
                                        sendUserToMainActivity();
                                        //editor.setHtml("<p>​hi Jarvis setup my day</p><p><br></p><p>Here&nbsp; is my program</p><p><br></p><h1><b>Get me <span style=\"background-color: rgb(255, 235, 59); color: rgb(255, 44, 147);\">all</span> i <span style=\"color: rgb(255, 44, 147); background-color: rgb(255, 235, 59);\">need</span> hey</b></h1><p><b><br></b></p>");
                                        Toast.makeText(PostActivity.this, "Article posted successfully.", Toast.LENGTH_LONG).show();
                                        loadingBar.dismiss();
                                    }
                                    else
                                    {
                                        Toast.makeText(PostActivity.this, "Error occurred while posting your article.", Toast.LENGTH_LONG).show();
                                        loadingBar.dismiss();
                                    }
                                }
                            });
                }
            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });
    }`

**Comment by cyberpunk922** [comment]
hi, thanks for your time. the getCurrentHtmlAsync() method works correctly.
the only problem was that the way it was stored in the firebase db

![whatsapp image 2018-12-30 at 11 54 44 pm 1](https://user-images.githubusercontent.com/20017250/50550074-0aa5b780-0c8f-11e9-9d86-533a778af784.jpeg)
