### ISSUE TITLE
How can I style the toolbar or include my own and call the styling options

### ISSUE THREAD

**Issue by ubarua123** [dankito/RichTextEditor#15]
Like i want to add my own horizontal scroll view, add buttons and then call Bold or italics etc.
Is there anyway I can do that?

**Comment by dankito** [comment]
Of course you can.

See for example 
    https://github.com/dankito/RichTextEditor/blob/master/RichTextEditorAndroid/src/main/kotlin/net/dankito/richtexteditor/android/toolbar/GroupedCommandsEditorToolbar.kt or 
    https://github.com/dankito/RichTextEditor/blob/master/RichTextEditorAndroid/src/main/kotlin/net/dankito/richtexteditor/android/toolbar/AllCommandsEditorToolbar.kt .
(Both are in Kotlin but shouldn't be hard to convert to Java.)

If I find some time the next few days I'm going to add some example code how to do this to the Readme.

Does this help you till then?

**Comment by dankito** [comment]
I added now an example to the README: https://github.com/dankito/RichTextEditor/tree/develop#customtoolbar

If it answers your question then please close this issue.

**Comment by ubarua123** [comment]
Thanks! Helps a lot.
