### ISSUE TITLE
how to insert image from local

### ISSUE THREAD

**Issue by kunz398** [dankito/RichTextEditor#16]
i have this so far

`<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <net.dankito.richtexteditor.android.RichTextEditor
        android:id="@+id/editor"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="10"
        />

    <net.dankito.richtexteditor.android.toolbar.AllCommandsEditorToolbar
        android:id="@+id/editorToolbar"
        android:layout_width="match_parent"
        android:layout_height="36dp"
        android:background="@color/colorPrimary"
        />

</LinearLayout>`

and my java file is a fragment which is like:
` editor = (RichTextEditor) rootView.findViewById(R.id.editor);

        editorToolbar = (AllCommandsEditorToolbar) rootView.findViewById(R.id.editorToolbar);
        editorToolbar.setEditor(editor);`

how can i insert images from local i tried the `editior.setpermission` but it doesnt work it says can not resolve method pleasehelp

**Comment by dankito** [comment]
If you just want to allow that the user can insert images, then by adding AllCommandsEditorToolbar your're done (I personally prefer the GroupedCommandsToolbar).

Just click on this command almost at the end of AllCommandsEditorToolbar

![image](https://user-images.githubusercontent.com/11586614/55111664-3b08c080-50db-11e9-9d94-4faebf7b3c13.png)


and then on the button with the three dots:

![image](https://user-images.githubusercontent.com/11586614/55111686-44922880-50db-11e9-9b08-68d0f3c526bb.png)




If you like to insert images programmatically, this can be done this way:

        editor = (RichTextEditor) findViewById(R.id.editor);

        editor.getJavaScriptExecutor().insertImage("<local path>", "<description>", 0);


Does this answer your question?

**Comment by kunz398** [comment]
so when i paste this part 
`      editor = (RichTextEditor) rootView.findViewById(R.id.editor);
        editor.getJavaScriptExecutor().insertImage("<local path>", "<description>", 0);
`
i get an error saying :
can not resolve getJavaScriptExecutor ...

**Comment by kunz398** [comment]
do i need to use kotlin or can i use java

**Comment by kunz398** [comment]
actually fixed it thank you 
u can close this now
