### ISSUE TITLE
change color of the popups 

### ISSUE THREAD

**Issue by kunz398** [dankito/RichTextEditor#18]
![image](https://user-images.githubusercontent.com/22246144/55213947-87760c80-5251-11e9-838f-f0cfb864c7c8.png)
since the image is white i can no see the select button how can i fix this

**Comment by dankito** [comment]
The buttons are using Android's buttonBarButtonStyle style.

I think as text color this style uses colorAccent.

Did you by incident set colorAccent to white?

If so you should be fine by defining colors like this in your src/main/res/values/colors.xml (if you derive your theme from RichTextEditorAppThemeLight or RichTextEditorAppThemeDark):

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <!-- light theme -->

    <color name="colorPrimary_Light">#0D47A1</color>
    <color name="colorPrimaryWithTransparency_Light">#570D47A1</color>
    <color name="colorPrimaryDark_Light">#1A237E</color>
    <color name="colorAccent_Light">#FF9100</color>

    <color name="primaryTextColor_Light">#000000</color>

    <color name="backgroundColor_Light">#969696</color>


    <!-- dark theme -->

    <color name="colorPrimary_Dark">#212121</color>
    <color name="colorPrimaryWithTransparency_Dark">#57212121</color>
    <color name="colorPrimaryDark_Dark">#000000</color>
    <color name="colorAccent_Dark">#FF9100</color>

    <color name="primaryTextColor_Dark">#bababa</color>

    <color name="backgroundColor_Dark">#303030</color>

</resources>
```


Does this fix the issue?

**Comment by kunz398** [comment]
yes it does thanks 
i overlooked it
