### ISSUE TITLE
how to upload image in server using php?

### ISSUE THREAD

**Issue by chunarakaran** [dankito/RichTextEditor#22]

**Comment by dankito** [comment]
Is there any question?

**Comment by chunarakaran** [comment]
I want to upload local image to server using php API

**Comment by dankito** [comment]
Sorry, i neither know PHP, nor is this question related to RichTextEditor. That's a complete other application.

You can find some suggestions how to do it here https://github.com/dankito/RichTextEditor/issues/5 or here https://github.com/dankito/RichTextEditor/issues/19 .

Is it OK for you when i close this issue then?
