### ISSUE TITLE
Play store gives security warning (update this jquery@1.12.4)

### ISSUE THREAD

**Issue by knjl34** [dankito/RichTextEditor#30]
hey,

As per google security policies changed they give me warning for this lib.

below are warning i have found !!

**Google warning:** I see that version 1.12.4 of your app has this file in it, which contains one or more libraries with known security issues:
JavaScript jquery 1.12.4 SNYK-npm:jquery:20110606, SNYK-npm:jquery:20150627, SNYK-JS-JQUERY-174006 assets/editor/jquery.js

And i have this one comes from this lib. so could you change it to latest version of js.
this one i have found in this lib. 
richtexteditor-android-2.0.12.aar: jquery.js (pkg:javascript/jquery@1

Please change it and let me know if you didn't get it.

**Comment by dankito** [comment]
Thank you so much for reporting this issue to me!

When I find some time this weekend I

a) going to update jQuery,

b) check if I can kick it out completely. Vanilla JavaScript now has most of it's features, shouldn't be necessary anymore.

**Comment by knjl34** [comment]
hey,

a) Its great if you could do this within one two days because we are releasing app and its showing that warning so if possible then please do !!
 
b) if completely remove will be create problem might be !! if possible without losing functionality will be great.

**Comment by dankito** [comment]
Actually don't know where this has been coming from. Couldn't see any import for jQuery, also wasn't checked in Git.

Removed it and release new 2.0.13 version.

Simply check if everything is still working (could find anything at first glance) and then may release your app.

**Comment by knjl34** [comment]
hey,

Yes now that warning gone in my analyzer let me update app in play store and its gone in 2.0.13 is the perfect form me !!

Cheers !!
