### ISSUE TITLE
JQuery version

### ISSUE THREAD

**Issue by tised** [dankito/RichTextEditor#32]
I received such a warning from Google in my console: 

<img width="990" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/14261987/73266364-6f5b7a80-41df-11ea-851c-3a32f57e180a.png">

I do not use JS in my project, other than your library: https://github.com/dankito/RichTextEditor/tree/release/2.0.x/RichTextEditorCommon/src/main/resources/editor

Can you confirm that it comes from your library, or I need to search for another dependency library which causes this problem

Very thank you!

**Comment by dankito** [comment]
Did you use the current version?

I had this issue: https://github.com/dankito/RichTextEditor/issues/30

But never found out where jQuery was coming from, never used it by myself.

So did this also occur with version >= 2.0.13?

**Comment by tised** [comment]
oops, sorry! 
didn't find that one
Will test and ping you

**Comment by knjl34** [comment]
hey,
same happen in my case and resolved in 2.0.13  

please check with that one 

its gone in 2.0.13 is the perfect form me !!

Cheers !!
