### ISSUE TITLE
How to customize blockquotes

### ISSUE THREAD

**Issue by rezziqbal06** [dankito/RichTextEditor#35]
How to costumize blockquote in editor to appear vertical line before text?

**Comment by dankito** [comment]
Hi,

as the underlying implementation uses HTML / JavaScript you can simply style it with CSS.

Place a file called 'platform_style.css' in your app's src/main/assets folder and style the blockquote element there:

```
blockquote {
   // your custom style here
}
```

**Comment by rezziqbal06** [comment]
Thank you for your response

**Comment by rezziqbal06** [comment]
One thing i wanna ask,
Can i set font in editor from src/main/res/fonts ? How to do that?

**Comment by dankito** [comment]
It's true, currently I list only system fonts (see files SystemFontsParser and FontNamesUtils and the according commands SetFontNameCommand and SetFontNameWithPreviewCommand).

But I really don't know how 

a) a custom font can be used generally in Android's WebView,

b) how this then can be configured to use this custom font via JavaScript.

If you can give me any hint how to do this or even better give me a pull request with working code I can implement this.

But in general: For new questions please open a new issue.
