### ISSUE TITLE
Image resizable inside of richtexteditor 

### ISSUE THREAD

**Issue by tised** [dankito/RichTextEditor#44]
Hello!
Our testers found a weird thing with pictures which user able to add to this component if you will tap on corner of the image - you will able to resize it
Also you able to rotate an image by 2 fingers and all these changes are saved to a <img> tag

Can we disable that somehow?
Or maybe you will add a flag to editor settings "imagesEditable" for example

Thanks!

**Comment by dankito** [comment]
It's a feature, not a bug :).

Another user implemented this so that users can adjust image sizes: https://github.com/dankito/RichTextEditor/issues/1

And yes, you can disable this by calling:

```
editor.javaScriptExecutor.disableImageResizing()
```

**Comment by tised** [comment]
oh, great! I will check it
