### ISSUE TITLE
"+" character missing 

### ISSUE THREAD

**Issue by openmotion** [dankito/RichTextEditor#47]
when i type the "+" character, it's replaced by a " " (space) in the addHtmlChangedListener / htmlChangedAsync function

**Comment by openmotion** [comment]
this editor is ok wit the "+" character -> com.github.mthli:Knife:v1.1
this is the list of editors with the same bug :
com.github.lumyjuwon:Android-Rich-Wysiwyg-Editor:1.0.0
jp.wasabeef:richeditor-android:1.2.2

this one is web/javascript and no problem but app crash randomly when displayed in a popup window (fragment) :
in.nashapp.androidsummernote:androidsummernote:1.0.5

**Comment by dankito** [comment]
Wasn't except one aware of all the other editors actually. But good to see that others have this bug too :).

Can confirm that in was to 100 % a bug.

Version 2.0.16 should fix that now (should be visible at Maven Central in maximum two hours).

If it fixes the issue for you would be great if you could close the ticket.

And thanks for reporting it to me!
