### ISSUE TITLE
How local image upload to server

### ISSUE THREAD

**Issue by sudipnandi01** [dankito/RichTextEditor#52]
if I upload an image to the server I get an image url, then I want to insert the image using this server image url. How i have to achieve this functionality?

**Comment by dankito** [comment]
You can call

```
RichTextEditor.javaScriptExecutor.insertImage(url: String, alt: String, rotation: Int = 0)
```
to insert an image at current cursor location.

Does this answer your question?

Soon you can also set image width and height:
```
open fun insertImage(url: String, alt: String, width: String? = null, height: String? = null, rotation: Int = 0)
```
