### ISSUE TITLE
Compile error: "More than one file was found with OS independent path 'editor/normalize.css'."

### ISSUE THREAD

**Issue by eikooo** [dankito/RichTextEditor#56]
I tried to compile the Demoapp with the current Android Studio, but I get the following error:

"More than one file was found with OS independent path 'editor/normalize.css'."

I tried a clean build with a freshly downloaded Android studio.

What could be wrong?

**Comment by dankito** [comment]
On which branch are you? By change on 'release/2.0.x'?

Just saw that there in  `RichTextEditor/DemoApp/build.gradle` the packaging options aren't the same as on the other branches. Compare e.g. with 'develop':

```
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'

        pickFirst 'editor/normalize.css'
        pickFirst 'editor/style.css'
        pickFirst 'editor/editor.html'
        pickFirst 'editor/interact.min.js'
        pickFirst 'editor/platform_style.css'
        pickFirst 'editor/rich_text_editor.js'
        pickFirst 'META-INF/RichTextEditorCommon.kotlin_module'
    }
```

**Comment by eikooo** [comment]
Yes, I used the lastest release branch. The demo app is compiling and running now, after adding the 'pickFirst ' lines. Thanks!
