### ISSUE TITLE
Failed to resolve dependencies

### ISSUE THREAD

**Issue by antranvn** [dankito/RichTextEditor#57]
Hello,
I'm running your demo app, however, there are issues regards dependencies.
Could you please help to check it?

**Failed to resolve: net.dankito.utils:java-utils:2.0.0-SNAPSHOT**
Show in Project Structure dialog
Affected Modules: RichTextEditorCommon

**Failed to resolve: net.dankito.utils:java-utils:2.0.0-SNAPSHOT**
Show in Project Structure dialog
Affected Modules: DemoApp

**Failed to resolve: net.dankito.utils:java-fx-utils:2.0.0-SNAPSHOT**
Show in Project Structure dialog
Affected Modules: RichTextEditorJavaFX

**Failed to resolve: net.dankito.utils:android-utils:2.0.0-SNAPSHOT**
Show in Project Structure dialog
Affected Modules: DemoApp, RichTextEditorAndroid

**Failed to resolve: net.dankito.filechooserdialog:filechooserdialog-android:1.2.1-SNAPSHOT**
Show in Project Structure dialog
Affected Modules: RichTextEditorAndroid

**Comment by eucliddelphi** [comment]
Hi,
about `fileChooserDialogVersion` not sure, I just left it as it is.
Go to the `versions.gradle` and change the values of the following version variables:

```
javaUtilsVersion = '1.0.16'
..............
javaFXUtilsVersion = '1.0.7'
```

You will find the latest repositories here: https://mvnrepository.com/artifact/net.dankito.utils

**Comment by kalpit-dev** [comment]
Hello,

After updating the versions, I am able to build but now I get another error:
**Unresolved reference: ImageReference**

Seems we need to specify a version that includes this file.

**Comment by dankito** [comment]
I'm really sorry, I accidentally merge develop to master.

As said in #58 please use branch 'release/2.0.x' in the meanwhile.

**Comment by kalpit-dev** [comment]
Thanks, it worked.

**Comment by kalpit-dev** [comment]
@dankito 

I am trying to integrate the library in my project.

However there is some conflicts between android-utils-1.1.1 and appcompat-v7-28.0.0 related to duplicate value of resource.

Which module do I need to exclude from android-utils-1.1.1?

![Uploading Screenshot 2020-10-24 at 3.56.20 PM.png…]()
