### ISSUE TITLE
Cannot build app

### ISSUE THREAD

**Issue by WendyYanto** [dankito/RichTextEditor#58]
Hi, currently I'm facing an issue after cloning from the repository. This issue is blocking me to run in my local : 

![image](https://user-images.githubusercontent.com/42958956/96095306-a4883400-0ef8-11eb-832c-33403896f1dc.png)

Is there any solutions ? Thank you

**Comment by eucliddelphi** [comment]
Please take a look in #57

**Comment by dankito** [comment]
Sorry many times I accidentally merged the unfinished develop branch to master!

Please checkout the branch 'release/2.0.x', it should work then.

**Comment by dankito** [comment]
`main` is now the default branch which also points now correctly to latest release from `release/2.0.x` branch. Please use that one.
