### ISSUE TITLE
Android 11 support

### ISSUE THREAD

**Issue by tised** [dankito/RichTextEditor#59]
Hello. I just updated my project to target Android 11, and seems you need to update some signatures because otherwise project won't build because of errors during compile time

Error: Inherited platform declarations clash: The following declarations have the same JVM signature (loadUrl(Ljava/lang/String;Ljava/util/Map;)V):

you have FullscreenWebView.kt file where you override 2 methods loadUrl

You have **NOT** nullable params there, which are **null** after android 11

Please update your overridden methods and let me know

Thanks!

**Comment by tised** [comment]
Hello! 

We are planning to target SDK 30 asap and I'm curious will you update your lib to target SDK 30? I cannot build project without your fix :)

**Comment by tised** [comment]
Hello, any news about Android 11 support ?

**Comment by dankito** [comment]
Sorry, i'm already working 14 - 18 hours a day and that 6 - 7 days a week.

Did it now in my holidays.

Just uploaded version 2.0.19 that should fix that issue (should be visible soon on Maven Central).

Do you know any Kotlin? As in this case it would have been much faster if you just would have fixed that issue and gave me a pull request.

If it works now, feel free to close the ticket.

(Please use version 2.0.20 as that fixes the issue with displaying images from local storage in Android 11, see #54.)

**Comment by tised** [comment]
Hello! Thanks for the updates!
Yes, Kotlin currently my main language for developing apps, I even did a fork of your lib and did changes needed for targeting SDK 30, but I had problems with the build, so I didn't do a pull request :(

As I understood you do not have much time right now if you want, I'll share my email address and we can resolve my issues with build and I will kindly help you with this repo :). My email is: tised.dev@gmail.com

The original issue is fixed, so I'm closing the issue

**Comment by dankito** [comment]
May as a introduction for future fixes:

Exclusively use the branch `release/2.0.x`.

In `RichTextEditorAndroid/build.gradle` and `RichTextEditorJavaFX/build.gradle` toogle the comments of these two lines under `dependencies` so that they look like this:

```
    implementation "$mavenGroup:$richTextEditorCommonMavenArtifactId:$version"
//    implementation project(":RichTextEditorCommon")
```

The first line is needed for uploads to Maven Central. But for local builds only the second one works when the (intermediate) version isn't uploaded to Maven Central yet.
