### ISSUE TITLE
Standard font family in RichTextEditor

### ISSUE THREAD

**Issue by wharnisch** [dankito/RichTextEditor#60]
Standard font family in RichTextEditor control seems to be "serif". So if if no font family is set, all text is shown as "serif" text.

In contrary to this standard font in base class WebView control seems to be "sans-serif". So if no font family is set, all text is shown as "sans-serif" text.

This leads to the situation that "serif" text written in RichTextEditor will be shown as "sans-serif".

How can I change this behaviour of RichTextEditor control? I want to use the RichTextEditor in a new app, solving this is crucial for usage.

I tried
`editor.setEditorFontFamily("sans-serif");`
and
`editor.post( () -> editor.setEditorFontFamily("sans-serif") );`
These sometimes work and sometimes do not work!

Thanks for your help!

Regards from Austria

**Comment by dankito** [comment]
I just guess it's a race condition. It takes some time till RichTextEditor is loaded. So depending on if it's already loaded the `editor.setEditorFontFamily("sans-serif");` call will work or not.

To fix that issue you can add a EditorLoadedListener (had that example only in MainActivity.kt, not in JavaShowCaseMainActivity.java, fixed that now):

```
editor.addEditorLoadedListener(new EditorLoadedListener() {
    @Override
    public void editorLoaded() {
        editor.setEditorFontFamily("sans-serif");
    }
});
```

Does this solve your issue?

**Comment by wharnisch** [comment]
Yes, thank you very much, now it works!
Regards from Austria
