### ISSUE TITLE
Reset "text color" and "text background color"

### ISSUE THREAD

**Issue by wharnisch** [dankito/RichTextEditor#62]
"text color" and "text background color" can be set using the two upper left tools of the toolbar. I did not find a way to reset "text color" and "text background color", so that no "text color" and no "text background color" is selected.

**Comment by dankito** [comment]
There's the `RemoveFormatCommand`.

In the toolbar you (probably) mentioned it's in the last line on the right side left to the redo command.

**Comment by wharnisch** [comment]
Tapping on the tool you probably mentioned (red circle) seems to be completely ignored. It definitely does not reset "text color" and "text background color"
![grafik](https://user-images.githubusercontent.com/20164700/106357597-4a747880-6307-11eb-9e1f-f48d731753f4.png)

**Comment by dankito** [comment]
Yes you are right.

As i just figured out: you have to select some text - the one that should not be formatted - and then press the command in the red circle.

Didn't find a better workaround for this, sorry.
